projects:
  NextBlog:
    schemaPath: graphql/schema.json
    includes:
      - ./graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: graphql
extensions:
  amplify:
    version: 3
